apiVersion: v1
appVersion: "latest"
description: A Matrix-Telegram hybrid puppeting/relaybot bridge - https://matrix.to/#/#telegram:maunium
name: mautrix-telegram
version: 0.1.0
keywords:
  - synapse
  - chat
  - matrix
  - bridge
  - telegram
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/tulir/mautrix-telegram
  - https://hub.docker.com/r/halkeye/mautrix-telegram
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
